flags:
  utilslib.fdroid:
    paths:
      - utilslib/src
    carryforward: false

  utilslib.googleplay:
    paths:
      - utilslib/src
    carryforward: false

  cloudlib.googleplay:
    paths:
      - cloudlib/src
    carryforward: false

  app.manifestTest:
    paths:
      - app/src
    carryforward: false

  app.froid:
    paths:
      - app/src
    carryforward: false

  app.gooleplay:
    paths:
      - app/src
    carryforward: false
