flags:
  app.manifestTest:
    carryforward: true

  app.froid:
    carryforward: true

  app.gooleplay:
    carryforward: true

ignore:
  - "**/androidTest/**/*.kt"
  - "**/androidTest/**/*.java"
  - "**/manifestTest/**/*.kt"
  - "**/manifestTest/**/*.java"
  - "**/test/**/*.kt"
  - "**/test/**/*.java"
