flags:
  utilslib.fdroid:
    carryforward: true

  utilslib.googleplay:
    carryforward: true

  cloudlib.googleplay:
    carryforward: true

  app.manifestTest:
    carryforward: true

  app.froid:
    carryforward: true

  app.gooleplay:
    carryforward: true
