name: App Center

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  job_assembleGoogleplay:
    name: assembleGoogleplay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: local.properties
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: assembleGoogleplay
        run: |
          set -x
          ./gradlew assembleGoogleplay

      - name: appcenter-cli
        run: |
          set -x
          npm install -g yarn
          npm install -g appcenter-cli
          yarn
          appcenter login --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          export APP_GOOGLEPLAY_DEBUG=app/build/outputs/apk/googleplay/debug/app-googleplay-debug.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Development" --file ${APP_GOOGLEPLAY_DEBUG} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent
          export APP_GOOGLEPLAY_RELEASE_UNSIGNED=app/build/outputs/apk/googleplay/release/app-googleplay-release-unsigned.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Production" --file ${APP_GOOGLEPLAY_RELEASE_UNSIGNED} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent
