name: coverage

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  coverage-app:
    name: coverage-app
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :app:testManifestTestDebugCoverage :app:testFdroidDebugCoverage :app:testGoogleplayDebugCoverage

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: publish app.manifestTest
        run: |
          set -x
          ls -al app/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/ManifestTestDebug.xml -F app.manifestTest

      - name: publish app.froid
        run: |
          set -x
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/FdroidDebug.xml -F app.froid

      - name: publish app.gooleplay
        run: |
          set -x
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/GoogleplayDebug.xml -F app.gooleplay
