name: coverage

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  coverage-app:
    name: coverage-app
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: local.properties
        run: |
          touch local.properties
          echo ${{ secrets.LOCAL_PROPERTIES }} | base64 -d > local.properties
          touch QuoteUnquote.cloudLib/cloudLib/local.properties
          echo ${{ secrets.LOCAL_PROPERTIES_CLOUDLIB }} | base64 -d > QuoteUnquote.cloudLib/cloudLib/local.properties
          touch QuoteUnquote.utilsLib/utilsLib/local.properties
          echo ${{ secrets.LOCAL_PROPERTIES_UTILSLIB }} | base64 -d > QuoteUnquote.utilsLib/utilsLib/local.properties

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :app:testManifestTestDebugCoverage :app:testFdroidDebugCoverage :app:testGoogleplayDebugCoverage

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: publish
        run: |
          set -x
          ls -al app/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/ManifestTestDebug.xml -F app.manifestTest
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/FdroidDebug.xml -F app.froid
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/GoogleplayDebug.xml -F app.gooleplay
