name: coverage-androidTest

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_VERSION: 1
  API_LEVEL: 36

jobs:
  androidTest:
    name: ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 600
    strategy:
      fail-fast: true
      matrix:
        flavor: [ fdroid, googleplay ]
        include:
          - flavor: fdroid
            gradle_task: :app:connectedFdroidDebugAndroidTestCoverage
          - flavor: googleplay
            gradle_task: :app:connectedGoogleplayDebugAndroidTestCoverage

    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Clear Gradle cache
        run: ./ci_clear_gradle_cache.sh

      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.CACHE_VERSION }}-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}

      - name: Get AVD info
        uses: ./.github/actions/get-avd-info
        id: avd-info
        with:
          api-level: ${{ env.API_LEVEL }}

      - name: Cache AVD
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-avd-${{ env.CACHE_VERSION }}-${{ steps.avd-info.outputs.arch }}-${{ steps.avd-info.outputs.target }}-${{ env.API_LEVEL }}

      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot."

      - name: Write local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
          LOCAL_PROPERTIES_CLOUDLIB: ${{ secrets.LOCAL_PROPERTIES_CLOUDLIB }}
          LOCAL_PROPERTIES_UTILSLIB: ${{ secrets.LOCAL_PROPERTIES_UTILSLIB }}
        run: |
          echo "${LOCAL_PROPERTIES}" | base64 -d > local.properties
          echo "${LOCAL_PROPERTIES_CLOUDLIB}" | base64 -d > QuoteUnquote.cloudLib/cloudLib/local.properties
          echo "${LOCAL_PROPERTIES_UTILSLIB}" | base64 -d > QuoteUnquote.utilsLib/utilsLib/local.properties

      - name: Write google-services.json
        env:
          GOOGLE_PLAY_JSON_DEVELOPMENT: ${{ secrets.GOOGLE_PLAY_JSON_DEVELOPMENT }}
        run: echo "${GOOGLE_PLAY_JSON_DEVELOPMENT}" | base64 -d > app/google-services.json

      - name: Run androidTests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb logcat -c
            adb logcat > logcat.txt &
            ./gradlew ${{ matrix.gradle_task }} --stacktrace

      - name: Upload logcat
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.flavor }}-logcat-${{ env.API_LEVEL }}
          path: logcat.txt

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.flavor }}-${{ env.API_LEVEL }}
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*