name: coverage

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  coverage-app-googleplay:
    name: coverage-app-googleplay
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :app:testGoogleplayDebugCoverage

      - name: publish app.gooleplay
        run: |
          set -x
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/GoogleplayDebug.xml -F app.gooleplay

  coverage-app-fdroid:
    name: coverage-app-fdroid
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :app:testFdroidDebugCoverage

      - name: publish app.froid
        run: |
          set -x
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/FdroidDebug.xml -F app.froid

  coverage-app-manifest:
    name: coverage-app-manifest
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :app:testManifestTestDebugCoverage

      - name: publish app.manifestTest
        run: |
          set -x
          ls -al app/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f app/build/reports/ManifestTestDebug.xml -F app.manifestTest

  coverage-cloudLib-googleplay:
    name: coverage-cloudLib-googleplay
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: cloudlib
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :cloudlib:testGoogleplayDebugCoverage

      - name: publish
        run: |
          set -x
          ls -al cloudlib/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f cloudLib/build/reports/GoogleplayDebug.xml -F cloudlib.googleplay

  coverage-utilsLib-googleplay:
    name: coverage-utilsLib-googleplay
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: utilsLib
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :utilsLib:testGoogleplayDebugCoverage

      - name: publish
        run: |
          set -x
          ls -al utilsLib/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f utilsLib/build/reports/GoogleplayDebug.xml -F utilslib.googleplay


  coverage-utilsLib-fdroid:
    name: coverage-utilsLib-fdroid
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: utilsLib
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :utilsLib:testFdroidDebugCoverage

      - name: publish
        run: |
          set -x
          ls -al utilsLib/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f utilsLib/build/reports/FdroidDebug.xml -F utilslib.fdroid
