name: deploy-appcenter

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  OSSAR-Scan:
    name: OSSAR-Scan
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'

      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew checkstyle

  detekt:
    name: detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew detekt

  super-linter:
    name: super-linter
    needs: [OSSAR-Scan, checkstyle, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    name: ktlint
    needs: [OSSAR-Scan, checkstyle, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew ktlint

  lintManifestTestDebug:
    name: lintManifestTestDebug
    needs: [OSSAR-Scan, checkstyle, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew lintManifestTestDebug

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

  lintGooglePlayDebug:
    name: lintGooglePlayDebug
    needs: [OSSAR-Scan, checkstyle, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew lintGooglePlayDebug

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

  lintFdroidDebug:
    name: lintFdroidDebug
    needs: [OSSAR-Scan, checkstyle, detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew lintFdroidDebug

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

  assembleGoogleplay:
    environment:
      name: appcenter.ms
      url: https://appcenter.ms/
    name: assembleGoogleplay
    needs: [ktlint, super-linter, lintManifestTestDebug, lintGooglePlayDebug, lintFdroidDebug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: keystore.jks
        env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
        run: echo "$KEYSTORE_JKS" | base64 -d > app/keystore.jks

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: assembleGoogleplay
        run: |
          set -x
          ./gradlew :app:assembleGoogleplay
          find . -name "*.apk" -print

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: appcenter-cli
        run: |
          set -x
          npm install -g yarn
          npm install -g appcenter-cli
          yarn
          appcenter login --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          export APP_GOOGLEPLAY_DEBUG=app/build/outputs/apk/googleplay/debug/app-googleplay-debug.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Development" --file ${APP_GOOGLEPLAY_DEBUG} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent
          export APP_GOOGLEPLAY_RELEASE_UNSIGNED=app/build/outputs/apk/googleplay/release/app-googleplay-release.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Production" --file ${APP_GOOGLEPLAY_RELEASE_UNSIGNED} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent

  assembleFdroid:
    environment:
      name: appcenter.ms
      url: https://appcenter.ms/
    name: assembleFdroid
    needs: [ktlint, super-linter, lintManifestTestDebug, lintGooglePlayDebug, lintFdroidDebug]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > local.properties

      - name: keystore.jks
        env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
        run: echo "$KEYSTORE_JKS" | base64 -d > app/keystore.jks

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: assembleFdroid
        run: |
          set -x
          ./gradlew :app:assembleFdroid
          find . -name "*.apk" -print

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: appcenter-cli
        run: |
          set -x
          npm install -g yarn
          npm install -g appcenter-cli
          yarn
          appcenter login --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          export APP_FDROID_DEBUG=app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Development" --file ${APP_FDROID_DEBUG} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent
          export APP_FDROID_RELEASE_UNSIGNED=app/build/outputs/apk/fdroid/release/app-fdroid-release-unsigned.apk
          appcenter distribute release --app "jameshnsears/QuoteUnquote-Production" --file ${APP_FDROID_RELEASE_UNSIGNED} --group Collaborators --release-notes "GitHub CI" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }} --silent
